name: Deploy to AWS

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install application dependencies
        run: npm ci

      - name: Check code is formatted correctly
        run: npm run checkformat

      - name: Check code conforms to linting rules
        run: npm run lint

      - name: Check tests run
        run: npm run test

      - name: Deploy - dev
        if: github.ref == 'refs/heads/dev'
        run: npm run deploy:dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          SSL_CERTIFICATE_ARN: ${{ secrets.DEV_SSL_CERTIFICATE_ARN }}
          DEPLOY_ENVIRONMENT: dev
          DOMAIN_NAME: api.v1.courses.dev.app.york.ac.uk

      - name: Add AWS tags to API resources - dev
        if: github.ref == 'refs/heads/dev'
        run: scripts/addAwsTagsToApi uoy-courses-api-v1 dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      - name: Deploy - production
        if: github.ref == 'refs/heads/main'
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}
          SSL_CERTIFICATE_ARN: ${{ secrets.PRODUCTION_SSL_CERTIFICATE_ARN }}
          DEPLOY_ENVIRONMENT: prod
          DOMAIN_NAME: api.v1.courses.app.york.ac.uk

      - name: Add AWS tags to API resources - production
        if: github.ref == 'refs/heads/main'
        run: scripts/addAwsTagsToApi uoy-courses-api-v1 prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
