name: Report Package Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v3

      - name: Check and report changes in the application's package size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: package
          pattern: .serverless/*.zip
          compression: none
          minimum-change-threshold: 1024
        env:
          AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
